'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
'
Namespace WebReferenceS01
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebServiceCalcSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebServiceCalc
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ws1.nopadol.com/webservicecalc.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginHelloWorld(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("HelloWorld", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndHelloWorld(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcurate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Calcurate(ByVal x As Double, ByVal y As Double) As Double
            Dim results() As Object = Me.Invoke("Calcurate", New Object() {x, y})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Function BeginCalcurate(ByVal x As Double, ByVal y As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Calcurate", New Object() {x, y}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCalcurate(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vGetData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vGetData(ByVal vBarCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("vGetData", New Object() {vBarCode})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginvGetData(ByVal vBarCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vGetData", New Object() {vBarCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvGetData(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vGetDataBarCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vGetDataBarCode(ByVal vBarCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("vGetDataBarCode", New Object() {vBarCode})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginvGetDataBarCode(ByVal vBarCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vGetDataBarCode", New Object() {vBarCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvGetDataBarCode(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vExecuteQuery", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vExecuteQuery(ByVal vStrQuery As String) As Integer
            Dim results() As Object = Me.Invoke("vExecuteQuery", New Object() {vStrQuery})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginvExecuteQuery(ByVal vStrQuery As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vExecuteQuery", New Object() {vStrQuery}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvExecuteQuery(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vGetQueryAnlyzer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vGetQueryAnlyzer(ByVal vStrQuery As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("vGetQueryAnlyzer", New Object() {vStrQuery})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginvGetQueryAnlyzer(ByVal vStrQuery As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vGetQueryAnlyzer", New Object() {vStrQuery}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvGetQueryAnlyzer(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vLogIn", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vLogIn(ByVal vUserID As String, ByVal vPassWord As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("vLogIn", New Object() {vUserID, vPassWord})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginvLogIn(ByVal vUserID As String, ByVal vPassWord As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vLogIn", New Object() {vUserID, vPassWord}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvLogIn(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vCheckUserID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vCheckUserID(ByVal vUserID As String, ByVal vPassWord As String) As Integer
            Dim results() As Object = Me.Invoke("vCheckUserID", New Object() {vUserID, vPassWord})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginvCheckUserID(ByVal vUserID As String, ByVal vPassWord As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vCheckUserID", New Object() {vUserID, vPassWord}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvCheckUserID(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vUserAccess", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vUserAccess(ByVal vPersonID As String, ByVal vPassWord As String) As Integer
            Dim results() As Object = Me.Invoke("vUserAccess", New Object() {vPersonID, vPassWord})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginvUserAccess(ByVal vPersonID As String, ByVal vPassWord As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("vUserAccess", New Object() {vPersonID, vPassWord}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndvUserAccess(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
End Namespace
